name: Rust checks

# turn off for now

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  main:
    name: Run check, test and lints
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        shell: bash
        run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

      - name: Install components
        shell: bash
        run: rustup component add clippy rustfmt

      - name: Run format check
        shell: bash
        run: cargo fmt --all --check

      - name: Run clippy
        shell: bash
        run: cargo clippy --all-targets

      - name: Run tests
        shell: bash
        run: cargo test --workspace
